export const links = [
    { name: 'Departments', url: '/' },
    { name: 'Rooms', url: '/rooms' },
]

export const departments = [
    {
        id: 1,
        name: "Emergency Room",
        phone_number: "555-123-4567",
        total_rooms: 10,
        available_rooms: 4,
        total_doctors: 25,
        description: "Provides immediate medical care for urgent and life-threatening conditions.",
    },
    {
        id: 2,
        name: "Cardiology",
        phone_number: "555-234-5678",
        total_rooms: 10,
        available_rooms: 5,
        total_doctors: 25,
        description: "Specializes in the diagnosis and treatment of heart conditions.",
    },
    {
        id: 3,
        name: "Oncology",
        phone_number: "555-345-6789",
        total_rooms: 10,
        available_rooms: 5,
        total_doctors: 25,
        description: "Treats cancer and related disorders.",
    },
    {
        id: 4,
        name: "Pediatrics",
        phone_number: "555-456-7890",
        total_rooms: 10,
        available_rooms: 5,
        total_doctors: 25,
        description: "Provides healthcare for children and adolescents.",
    },
    {
        id: 5,
        name: "Neurology",
        phone_number: "555-567-8901",
        total_rooms: 10,
        available_rooms: 5,
        total_doctors: 25,
        description: "Deals with disorders of the nervous system.",
    },
    {
        id: 6,
        name: "Psychiatry",
        phone_number: "555-678-9012",
        total_rooms: 10,
        available_rooms: 5,
        total_doctors: 25,
        description: "Provides mental health care.",
    },
    {
        id: 7,
        name: "Surgery",
        phone_number: "555-789-0123",
        total_rooms: 10,
        available_rooms: 5,
        total_doctors: 25,
        description: "Performs surgical procedures.",
    },
    {
        id: 8,
        name: "Obstetrics & Gynecology",
        phone_number: "555-890-1234",
        total_rooms: 10,
        available_rooms: 5,
        total_doctors: 25,
        description: "Provides care for women's reproductive health.",
    },
    {
        id: 9,
        name: "Radiology",
        phone_number: "555-901-2345",
        total_rooms: 10,
        available_rooms: 5,
        total_doctors: 25,
        description: "Uses imaging techniques to diagnose and treat diseases.",
    },
    {
        id: 10,
        name: "Pathology",
        phone_number: "555-012-3456",
        total_rooms: 10,
        available_rooms: 5,
        total_doctors: 25,
        description: "Analyzes tissue samples to diagnose diseases.",
    },
];

export const rooms = [
    {
        id: 1,
        room_number: "101",
        status: "occupied",
        department_name: "Cardiology",
        type: "surgical",
        beds_number: 1,
    },
    {
        id: 2,
        room_number: "102",
        status: "vacant",
        department_name: "General Surgery",
        type: "ICU",
        beds_number: 2,
    },
    {
        id: 3,
        room_number: "103",
        status: "occupied",
        department_name: "Pediatrics",
        type: "surgical",
        beds_number: 1,
    },
    {
        id: 4,
        room_number: "201",
        status: "Under Maintenance",
        department_name: "Emergency",
        type: "ICU",
        beds_number: 4,
    },
    {
        id: 5,
        room_number: "202",
        status: "occupied",
        department_name: "Obstetrics",
        type: "surgical",
        beds_number: 1,
    },
    {
        id: 6,
        room_number: "203",
        status: "vacant",
        department_name: "Neurology",
        type: "ICU",
        beds_number: 2,
    },
    {
        id: 7,
        room_number: "301",
        status: "occupied",
        department_name: "Oncology",
        type: "surgical",
        beds_number: 1,
    },
    {
        id: 8,
        room_number: "302",
        status: "vacant",
        department_name: "Orthopedics",
        type: "ICU",
        beds_number: 2,
    },
    {
        id: 9,
        room_number: "303",
        status: "occupied",
        department_name: "Psychiatry",
        type: "surgical",
        beds_number: 1,
    },
];