export const links = [
    { name: 'Departments', url: '/' }
]

export const departments = [
    {
        id: 1,
        name: "Emergency Room",
        phone_number: "555-123-4567",
        total_rooms: 10,
        available_rooms: 4,
        total_doctors: 25,
        description: "Provides immediate medical care for urgent and life-threatening conditions.",
    },
    {
        id: 2,
        name: "Cardiology",
        phone_number: "555-234-5678",
        total_rooms: 10,
        available_rooms: 5,
        total_doctors: 25,
        description: "Specializes in the diagnosis and treatment of heart conditions.",
    },
    {
        id: 3,
        name: "Oncology",
        phone_number: "555-345-6789",
        total_rooms: 10,
        available_rooms: 5,
        total_doctors: 25,
        description: "Treats cancer and related disorders.",
    },
    {
        id: 4,
        name: "Pediatrics",
        phone_number: "555-456-7890",
        total_rooms: 10,
        available_rooms: 5,
        total_doctors: 25,
        description: "Provides healthcare for children and adolescents.",
    },
    {
        id: 5,
        name: "Neurology",
        phone_number: "555-567-8901",
        total_rooms: 10,
        available_rooms: 5,
        total_doctors: 25,
        description: "Deals with disorders of the nervous system.",
    },
    {
        id: 6,
        name: "Psychiatry",
        phone_number: "555-678-9012",
        total_rooms: 10,
        available_rooms: 5,
        total_doctors: 25,
        description: "Provides mental health care.",
    },
    {
        id: 7,
        name: "Surgery",
        phone_number: "555-789-0123",
        total_rooms: 10,
        available_rooms: 5,
        total_doctors: 25,
        description: "Performs surgical procedures.",
    },
    {
        id: 8,
        name: "Obstetrics & Gynecology",
        phone_number: "555-890-1234",
        total_rooms: 10,
        available_rooms: 5,
        total_doctors: 25,
        description: "Provides care for women's reproductive health.",
    },
    {
        id: 9,
        name: "Radiology",
        phone_number: "555-901-2345",
        total_rooms: 10,
        available_rooms: 5,
        total_doctors: 25,
        description: "Uses imaging techniques to diagnose and treat diseases.",
    },
    {
        id: 10,
        name: "Pathology",
        phone_number: "555-012-3456",
        total_rooms: 10,
        available_rooms: 5,
        total_doctors: 25,
        description: "Analyzes tissue samples to diagnose diseases.",
    },
];
